### ISSUE TITLE
Some compile warnings

### ISSUE THREAD

**Issue by posophe** [Ancurio/SDL_sound#1]
Hi !

My building of SDL2_sound fails with many warnings 
ogg.c: In function 'OGG_read':
[  151s] ogg.c:301:30: warning: pointer targets in passing argument 2 of 'ov_read' differ in signedness [-Wpointer-sign]
[  151s]              rc = ov_read(vf, buffer_start_point, bytes_remaining,
[  151s]                               ^
[  151s] In file included from ogg.c:52:0:
[  151s] /usr/include/vorbis/vorbisfile.h:194:13: note: expected 'char *' but argument is of type 'Uint8 \* {aka unsigned char *}'
[  151s]  extern long ov_read(OggVorbis_File *vf,char *buffer,int length,
[  151s]              ^
[  151s] raw.c: In function 'RAW_open':
[  151s] raw.c:99:16: warning: unused variable 'rw' [-Wunused-variable]
[  151s]      SDL_RWops *rw = internal->rw;

[  151s] shn.c: In function 'SHN_read':
[  151s] shn.c:1073:12: warning: unused variable 'cpyBytes' [-Wunused-variable]
[  151s]      Uint32 cpyBytes = 0;
[  151s]             ^
[  151s] shn.c: In function 'SHN_rewind':
[  151s] shn.c:1310:12: warning: unused variable 'shn' [-Wunused-variable]
[  151s]      shn_t *shn = (shn_t *) internal->decoder_private;
[  151s]             ^

[  152s] flac.c: In function 'FLAC_read':
[  152s] flac.c:543:12: warning: unused variable 'len' [-Wunused-variable]
[  152s]      Uint32 len;
[  152s]             ^

[  152s] speex.c: In function 'process_header':
[  152s] speex.c:140:10: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
[  152s]      mode = speex_mode_list[header.mode];
[  152s]           ^
[  152s] speex.c: In function 'SPEEX_open':
[  152s] speex.c:189:12: warning: unused variable 'buffer' [-Wunused-variable]
[  152s]      Uint8 *buffer = NULL;
[  152s]             ^
[  152s] libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I../decoders/timidity -fvisibility=hidden -I/usr/include/SDL2 -D_REENTRANT -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -D_REENTRANT -D_THREAD_SAFE -c wav.c  -fPIC -DPIC -o .libs/wav.o
[  153s] In file included from wav.c:44:0:
[  153s] wav.c: In function 'read_fmt_chunk':
[  153s] wav.c:211:34: warning: pointer targets in passing argument 2 of 'read_le32' differ in signedness [-Wpointer-sign]
[  153s]      BAIL_IF_MACRO(!read_le32(rw, &fmt->chunkSize), NULL, 0);
[  153s]                                   ^
[  153s] ../SDL_sound_internal.h:308:36: note: in definition of macro 'BAIL_IF_MACRO'
[  153s]  #define BAIL_IF_MACRO(c, e, r) if (c) { **Sound_SetError(e); return r; }
[  153s]                                     ^
[  153s] wav.c:85:23: note: expected 'Uint32 \* {aka unsigned int *}' but argument is of type 'Sint32 \* {aka int *}'
[  153s]  static __inline** int read_le32(SDL_RWops *rw, Uint32 *ui32)
[  153s]                        ^
[  153s] In file included from wav.c:44:0:
[  153s] wav.c:215:34: warning: pointer targets in passing argument 2 of 'read_le16' differ in signedness [-Wpointer-sign]
[  153s]      BAIL_IF_MACRO(!read_le16(rw, &fmt->wFormatTag), NULL, 0);
[  153s]                                   ^
[  153s] ../SDL_sound_internal.h:308:36: note: in definition of macro 'BAIL_IF_MACRO'
[  153s]  #define BAIL_IF_MACRO(c, e, r) if (c) { **Sound_SetError(e); return r; }
[  153s]                                     ^
[  153s] wav.c:75:23: note: expected 'Uint16 \* {aka short unsigned int *}' but argument is of type 'Sint16 \* {aka short int *}'
[  153s]  static __inline** int read_le16(SDL_RWops *rw, Uint16 *ui16)
[  153s]                        ^
[  153s] In file included from wav.c:44:0:
[  153s] wav.c: In function 'read_data_chunk':
[  153s] wav.c:249:34: warning: pointer targets in passing argument 2 of 'read_le32' differ in signedness [-Wpointer-sign]
[  153s]      BAIL_IF_MACRO(!read_le32(rw, &data->chunkSize), NULL, 0);
[  153s]                                   ^
[  153s] ../SDL_sound_internal.h:308:36: note: in definition of macro 'BAIL_IF_MACRO'
[  153s]  #define BAIL_IF_MACRO(c, e, r) if (c) { **Sound_SetError(e); return r; }
[  153s]                                     ^
[  153s] wav.c:85:23: note: expected 'Uint32 \* {aka unsigned int *}' but argument is of type 'Sint32 \* {aka int *}'
[  153s]  static __inline** int read_le32(SDL_RWops *rw, Uint32 *ui32)
[  153s]                        ^
[  153s] In file included from wav.c:44:0:
[  153s] wav.c: In function 'read_adpcm_block_headers':
[  153s] wav.c:376:38: warning: pointer targets in passing argument 2 of 'read_le16' differ in signedness [-Wpointer-sign]
[  153s]          BAIL_IF_MACRO(!read_le16(rw, &headers[i].iSamp1), NULL, 0);
[  153s]                                       ^
[  153s] ../SDL_sound_internal.h:308:36: note: in definition of macro 'BAIL_IF_MACRO'
[  153s]  #define BAIL_IF_MACRO(c, e, r) if (c) { **Sound_SetError(e); return r; }
[  153s]                                     ^
[  153s] wav.c:75:23: note: expected 'Uint16 \* {aka short unsigned int *}' but argument is of type 'Sint16 \* {aka short int *}'
[  153s]  static __inline** int read_le16(SDL_RWops *rw, Uint16 *ui16)
[  153s]                        ^
[  153s] In file included from wav.c:44:0:
[  153s] wav.c:379:38: warning: pointer targets in passing argument 2 of 'read_le16' differ in signedness [-Wpointer-sign]
[  153s]          BAIL_IF_MACRO(!read_le16(rw, &headers[i].iSamp2), NULL, 0);
[  153s]                                       ^
[  153s] ../SDL_sound_internal.h:308:36: note: in definition of macro 'BAIL_IF_MACRO'
[  153s]  #define BAIL_IF_MACRO(c, e, r) if (c) { **Sound_SetError(e); return r; }
[  153s]                                     ^
[  153s] wav.c:75:23: note: expected 'Uint16 \* {aka short unsigned int *}' but argument is of type 'Sint16 \* {aka short int *}'
[  153s]  static __inline** int read_le16(SDL_RWops *rw, Uint16 *ui16)
[  153s]                        ^
[  153s] wav.c: In function 'decode_adpcm_sample_frame':
[  153s] wav.c:439:15: warning: unused variable 'byte' [-Wunused-variable]
[  153s]          Uint8 byte;
[  153s]                ^
[  153s] wav.c:434:12: warning: unused variable 'delta' [-Wunused-variable]
[  153s]      Sint32 delta;
[  153s]             ^
[  153s] In file included from wav.c:44:0:
[  153s] wav.c: In function 'read_fmt_adpcm':
[  153s] wav.c:629:38: warning: pointer targets in passing argument 2 of 'read_le16' differ in signedness [-Wpointer-sign]
[  153s]          BAIL_IF_MACRO(!read_le16(rw, &fmt->fmt.adpcm.aCoef[i].iCoef1), NULL, 0);
[  153s]                                       ^
[  153s] ../SDL_sound_internal.h:308:36: note: in definition of macro 'BAIL_IF_MACRO'
[  153s]  #define BAIL_IF_MACRO(c, e, r) if (c) { **Sound_SetError(e); return r; }
[  153s]                                     ^
[  153s] wav.c:75:23: note: expected 'Uint16 \* {aka short unsigned int *}' but argument is of type 'Sint16 \* {aka short int *}'
[  153s]  static __inline** int read_le16(SDL_RWops *rw, Uint16 *ui16)
[  153s]                        ^
[  153s] In file included from wav.c:44:0:
[  153s] wav.c:630:38: warning: pointer targets in passing argument 2 of 'read_le16' differ in signedness [-Wpointer-sign]
[  153s]          BAIL_IF_MACRO(!read_le16(rw, &fmt->fmt.adpcm.aCoef[i].iCoef2), NULL, 0);
[  153s]                                       ^
[  153s] ../SDL_sound_internal.h:308:36: note: in definition of macro 'BAIL_IF_MACRO'
[  153s]  #define BAIL_IF_MACRO(c, e, r) if (c) { **Sound_SetError(e); return r; }
[  153s]                                     ^
[  153s] wav.c:75:23: note: expected 'Uint16 \* {aka short unsigned int *}' but argument is of type 'Sint16 \* {aka short int *}'
[  153s]  static __inline** int read_le16(SDL_RWops *rw, Uint16 *ui16)
[  153s]                        ^
[  153s] In file included from wav.c:44:0:
[  153s] wav.c: In function 'read_ima_block_headers':
[  153s] wav.c:677:38: warning: pointer targets in passing argument 2 of 'read_le16' differ in signedness [-Wpointer-sign]
[  153s]          BAIL_IF_MACRO(!read_le16(rw, &d[i].iPrevSamp), NULL, 0);
[  153s]                                       ^
[  153s] ../SDL_sound_internal.h:308:36: note: in definition of macro 'BAIL_IF_MACRO'
[  153s]  #define BAIL_IF_MACRO(c, e, r) if (c) { **Sound_SetError(e); return r; }
[  153s]                                     ^
[  153s] wav.c:75:23: note: expected 'Uint16 \* {aka short unsigned int *}' but argument is of type 'Sint16 \* {aka short int *}'
[  153s]  static __inline** int read_le16(SDL_RWops *rw, Uint16 *ui16)
[  153s]                        ^
[  153s] In file included from wav.c:44:0:
[  153s] wav.c: In function 'read_fmt_ima':
[  153s] wav.c:909:34: warning: pointer targets in passing argument 2 of 'read_le16' differ in signedness [-Wpointer-sign]
[  153s]      BAIL_IF_MACRO(!read_le16(rw, &extraBytes), NULL, 0);
[  153s]                                   ^
[  153s] ../SDL_sound_internal.h:308:36: note: in definition of macro 'BAIL_IF_MACRO'
[  153s]  #define BAIL_IF_MACRO(c, e, r) if (c) { **Sound_SetError(e); return r; }
[  153s]                                     ^
[  153s] wav.c:75:23: note: expected 'Uint16 \* {aka short unsigned int *}' but argument is of type 'Sint16 \* {aka short int *}'
[  153s]  static __inline** int read_le16(SDL_RWops *rw, Uint16 *ui16)
[  153s]                        ^
[  153s] In file included from wav.c:44:0:
[  153s] wav.c: In function 'find_chunk':
[  153s] wav.c:999:38: warning: pointer targets in passing argument 2 of 'read_le32' differ in signedness [-Wpointer-sign]
[  153s]          BAIL_IF_MACRO(!read_le32(rw, &siz), NULL, 0);
[  153s]                                       ^
[  153s] ../SDL_sound_internal.h:308:36: note: in definition of macro 'BAIL_IF_MACRO'
[  153s]  #define BAIL_IF_MACRO(c, e, r) if (c) { **Sound_SetError(e); return r; }
[  153s]                                     ^
[  153s] wav.c:85:23: note: expected 'Uint32 \* {aka unsigned int *}' but argument is of type 'Sint32 \* {aka int *}'
[  153s]  static __inline** int read_le32(SDL_RWops *rw, Uint32 *ui32)
[  153s]                        ^
[  153s] wav.c: In function 'WAV_open_internal':
[  153s] wav.c:1016:12: warning: unused variable 'pos' [-Wunused-variable]
[  153s]      Uint32 pos;
[  153s]             ^

[  154s] extra_rwops.c: In function 'RWops_RWRefCounter_new':
[  154s] extra_rwops.c:122:26: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
[  154s]              retval->seek = refcounter_seek;
[  154s]                           ^
[  154s] extra_rwops.c:123:26: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
[  154s]              retval->read = refcounter_read;
[  154s]                           ^
[  154s] extra_rwops.c:124:27: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
[  154s]              retval->write = refcounter_write;
[  154s]                            ^
[  154s] SDL_sound.c: In function 'Sound_NewSampleFromMem':
[  154s] SDL_sound.c:679:24: warning: passing argument 1 of 'SDL_RWFromMem' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
[  154s]      rw = SDL_RWFromMem(data, size);
[  154s]                         ^
[  154s] In file included from /usr/include/SDL2/SDL_audio.h:36:0,
[  154s]                  from /usr/include/SDL2/SDL.h:71,
[  154s]                  from SDL_sound.c:40:
[  154s] /usr/include/SDL2/SDL_rwops.h:164:36: note: expected 'void *' but argument is of type 'const Uint8 \* {aka const unsigned char *}'
[  154s]  extern DECLSPEC SDL_RWops *SDLCALL SDL_RWFromMem(void *mem, int size);

**Comment by Ancurio** [comment]
These are all warnings, where is the error that the compile fails on?

**Comment by posophe** [comment]
Sorry, was a mistake. It builds fine.

**Comment by posophe** [comment]
Could you rename the lib to libSDL2_sound to avoid conflicting with one compiling with SDL1 ? All major distros are still providing libSD_sound.

**Comment by Ancurio** [comment]
I would do it, if I was more experienced with autotools and confident I wouldn't mess up the rename somewhere =P

The whole autotools project itself could probably use a lot of maintenance work to get it to the same level as SDL2_image, SDL2_mixer etc..

**Comment by posophe** [comment]
Ah ok. For the moment, I'll just try to get mkxp building.
