### ISSUE TITLE
libtool: warning: undefined symbols not allowed in x86_64-w64-mingw32 shared libraries; building static only

### ISSUE THREAD

**Issue by hanetzer** [Ancurio/SDL_sound#3]
Apparently as it currently stands this project's build system won't produce a shared library (either via gentoo's crossdev or arch linux's mingw-w64 PKGBUILDs on the aur) due to undefined symbols.

Do you think it would be possible to fix this up in the future?

**Comment by Ancurio** [comment]
Sure. How do I fix it?

Edit: Have you tried [this](https://stackoverflow.com/questions/17487891/libtool-undefined-symbols-not-allowedin-i686-pc-mingw32-shared)?

**Comment by hanetzer** [comment]
heh. therein lies the problem, if I knew how to fix it I'd just send you a pr. I'm in the autotools channel awaiting a response, but none is forthcoming at the moment. Mostly just bringing this to publicish attention for the record.

**Comment by hanetzer** [comment]
@Ancurio and there we go. I knew `-no-undefined` had to be passed in somewhere, I just wasn't sure where. Adding `-no-undefined` into `Makefile.am` in `libSDL_sound_la_LDFLAGS` allows the building of a dll.

**Comment by NHDaly** [comment]
(for others like me who come across this on google, this was fixed here: https://github.com/Ancurio/SDL_sound/pull/4)
